github:
  description: "Semi-official Apache CouchDB Docker images"
  homepage: https://github.com/apache/couchdb-docker
  labels:
    - apache
    - couchdb
    - erlang
    - network-client
    - http
    - cplusplus
    - big-data
    - cloud
    - database
    - network-server
    - javascript
  protected_branches:
    main:
      required_status_checks:
        strict: true
      required_pull_request_reviews:
        # Set to true if you want to automatically dismiss approving reviews when someone pushes a new commit.
        dismiss_stale_reviews: false
        # Specifies the number of reviewers required to approve pull requests.
        # Use a number between 1 and 6 or 0 to not require reviewers.
        required_approving_review_count: 1

